[build]
# command = 'git submodule update --init --recursive && hugo --gc --minify'
command = 'hugo --gc --minify'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.147.7'
HUGO_ENV = 'production'
